name: Run
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/fabianMendez/bits
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go run cmd/main.go
